# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "oB8eSlECEUiJtyqNeEV1RCKh/ETng6q5voTz4m/FNgt/sb4+m5zAiPpMnQkpMmpItnOGeA+lHbIBOAZAxnb5fjZutT0wZXM5j+/ynhwLRP5aipB4eNZYsaFhTtYGabFwlYTf4SoSpzH80lpx7Eck/fUa63gd57KiaglyVINM5F9MnliXqZ5YZS5sBcgz6/urgZ9lRuqGE9pz+k5ux0J8l8D6R95qtg5dVXoqbjmTZW86mqzPBLfmvVvVkVBCLpzwooM9ZVZQpjjB4pBMEQ6uVI8D+XJux3fkefB1Mw7e52Ln5gPMcRsjbnJHf48txKVG5k6DO7nw8Ufzud74Smg5TmLUHsCyDa7Ul1bBWz1YcerXYuNZ/dPofJAL1sh2Sv3i3txNzbdSobYwtx3zPeQrEXypzkZI2/6y3uzcfogc7fNa/bXfxaLRSEd38KnsaiakSFq4oL5E8KhYS5O2kR6jhDlWnDs9/Z15FKPEr8Ybp21uuTTHVCUfqRrQDG7Nze5j9tiMOel66F8dQcJL7L19KV8WQqzoV+WyEJJMGZ7Bh7pC9hinKpMZyNo/u2ZG1J42qMvVqbTCW8x8+FeuoEPHhD9wTB21Dunl3Ac1OjRb8mn7U+3SJYgnYSSzsnArSSfRqBTBXzTonOOnH/D5yTAkoUykkIhxySsl0juLDj5WvDk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
